### ISSUE TITLE
Deleted variables

### ISSUE THREAD

**Issue by bombjackit** [SerafinTech/node-red-contrib-cip-st-ethernet-ip#11]
**Is your feature request related to a problem? Please describe.**
If, for error, a variable readed from a plc is deleted, eth-in stop reading all variables.

**Describe the solution you'd like**
Instead stop reading all variables, it is better to report which variables are impossible to read, and continue to read the other variable (for example reporting status with yellow status)

**Comment by GeekMeUpScotty** [comment]
@bombjackit You are referring to variables defined in the tag list, but they are deleted on the PLC, right? My recent pull requests that are already merged should fix this. At least to the extent that remaining variables are still being read. Did you try with latest release? For reporting the missing variables - I have a pull request pending that will do just that - by adding an extra output to the Eth-in node (See #9 ). But I don't know if @SerafinTech want's to merge that :)

**Comment by bombjackit** [comment]
@GeekMeUpScotty I will try when possible : I saw that your commit is in version 2.0.2

**Comment by SerafinTech** [comment]
@GeekMeUpScotty still looking for time to test

**Comment by SerafinTech** [comment]
All done.  Added error reporting if extra output not selected. Published 2.0.3 to NPM

**Comment by GeekMeUpScotty** [comment]
@SerafinTech Nice! I also considered that.
One question though. If I read the code correctly, this will throw exactly one catchable error no matter how many times a specific unknown tag is encountered. This can very well be sane - but what if there are two (or more) unknown tags? No additional errors will be thrown until the flow is restarted, no?

**Comment by bombjackit** [comment]
I tried versione 2.0.2 and if a variable does not exists it return only that variable with data null : great work.
