### ISSUE TITLE
Plc is not automatically reconnected

### ISSUE THREAD

**Issue by bombjackit** [SerafinTech/node-red-contrib-cip-st-ethernet-ip#5]
### Describe the bug
When a plc, for a known reason (like maintenance, firmware upgrade or software upload), is disconnected from the lan, sometimes it does not automatically reconnect : I have to restart flow manually.

### Expected behavior
I expect that the plc is reconnected, in all case, automatically

### Logs
This is the log (after this plc is disconnected)
26 Jun 08:03:27 - [error] [eth-ip endpoint:Plc] Error communicating with the PLC: {"generalStatusCode":4,"extendedStatus":[0]}

### Environment
 - node-red-contrib-cip-st-ethernet-ip 2.0.0-beta.3
 - Node red 2.2.2
 - Node.JS 14.21.1
 - Plc Rockwell 1756L81ES
 - Windows 10 professional 21H2

**Comment by bombjackit** [comment]
Original post https://github.com/st-one-io/node-red-contrib-cip-ethernet-ip/issues/39

**Comment by bombjackit** [comment]
I see commit https://github.com/SerafinTech/ST-node-ethernet-ip/commit/cc9b24178466370f5471d0b75271d9a94179f799, maybe resolve my problem, I'll try soon

**Comment by SerafinTech** [comment]
Fixed

**Comment by bombjackit** [comment]
I tried automatic reconnect after download to plc (with node-red-contrib-cip-st-ethernet-ip 2.0.2) and all go well.
