### ISSUE TITLE
Add tag mappings, timestamps and grouping support

### ISSUE THREAD

**Issue by GeekMeUpScotty** [SerafinTech/node-red-contrib-cip-st-ethernet-ip#7]
**Is your feature request related to a problem? Please describe.**
I am with a customer where the scientists have a strong desire to add (meaningful) mappings to the PLC tags.
Also they would like to have timestamps attached directly to the read data.
Finally they want the collected data to be grouped, so that they can pass it on for further processing without massaging the msg  elements.

**Describe the solution you'd like**
I am opting for a non-breaking addition where mappings and grouping/timestamp inclusion can be added in the config node.

**Describe alternatives you've considered**
The only alternative is to add the desired logic in the flow after the data has been collected which clutters up the flow.

**Additional context**
I will submit a pull request that implements the desired behavior.

**Comment by GeekMeUpScotty** [comment]
@SerafinTech What is the prospect of merging the suggested pull request?
I have another pending PR that ties to https://github.com/SerafinTech/ST-node-ethernet-ip/pull/58. But I wrote the PR "on top" of the PR relating to this issue (#8), which is why I haven't submitted it yet. I just need to know whether I need to rewrite my PR so it can be merged on top of current master instead. Obviously I would prefer to have this merged as is :)

**Comment by SerafinTech** [comment]
Merged and published

**Comment by GeekMeUpScotty** [comment]
Perfect.. Thanks!
